### ISSUE TITLE
Peer review code 07-02

### ISSUE THREAD

**Issue by GiovanniKaaijk** [damian1997/web-app-from-scratch-1920#1]
https://github.com/damian1997/web-app-from-scratch-1920/blob/c25b9438fde7a276b2337614e72f51b1accfc15a/docs/js/app.js#L6
- Classmates is a global variable, so there is no need to use it as a param

https://github.com/damian1997/web-app-from-scratch-1920/blob/c25b9438fde7a276b2337614e72f51b1accfc15a/docs/js/app.js#L17
- Well done on creating an async loop, you might want to check .map instead of a classic loop.

**Comment by damianveltkamp** [comment]
Fixed after refactoring
